# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Science Magic # Make a title for your blog
email: sspackman99@gmail.com # Add your email 
description: "Welcome to Data Science Magic! This blog is the creation of a humble traveler in the world of data science, just like you.
My goal is to share what I know about data science with you with the hope of learning a little more myself as I go along. Enjoy!"
baseurl: "/stat386-projects" # keep this the same or change it to the name of the repository 
url: "https://www.datasciencemagic.org/" #  change this to "https://<your-github-username>.github.io"
image: "assets/images/good_vibes.jpeg"
author: Sam Spackman
copyright: SS # Your initials or what you want the copyright to be.  Leave empty for no copyright

# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: 
github_username:  sspackman99
linkedin_username: Sam Spackman
dribbble_username: 
facebook_username:
flickr_username:
instagram_username: 
pinterest_username:
youtube_username: 
googleplus_username:


# Build settings
# removed minima theme to a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
